# Generated by Django 6.0.1 on 2026-02-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
