# Generated by Django 6.0.1 on 2026-03-01 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_likes_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_per_user_post',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
